#!/usr/bin/env bash
# kody-celld container entrypoint. Modes:
#   single   one celld node with local durable state under $KODY_STATE_DIR (default)
#   deploy   render the fleet config from env and publish the Worker to $CELLD_BUCKET
#   node     run a fleet node against $CELLD_BUCKET (celld reads its own CELLD_* env)
#   celld    pass the remaining arguments straight to the celld binary
#   sh       drop into a shell
set -euo pipefail

mode="${1:-single}"
shift || true
state_dir="${KODY_STATE_DIR:-/data}"
port="${PORT:-8080}"

# Compose passes unset optional variables through as empty strings; celld wants
# them absent.
for optional in S3_ENDPOINT $(compgen -v | grep '^KODY_' || true); do
	if [[ -z "${!optional:-}" ]]; then unset "$optional"; fi
done

# Runtime limits / quota defaults (docs/operations.md) are plain KODY_* vars
# that the Worker reads from its bindings; list the ones that are set.
tunable_vars() {
	compgen -v | grep -E '^KODY_(EXECUTE|RUN|RESPONSE|AUDIT|MCP|QUOTA|AI|SEARCH|VECTOR|QDRANT|BLOB|BROWSER)_' |
		grep -v '^KODY_BROWSER_ALLOW_PRIVATE_HOSTS$' || true
}

random_hex() {
	node -e 'process.stdout.write(require("node:crypto").randomBytes(Number(process.argv[1])).toString("hex"))' "$1"
}

# Operator values live in $state_dir/kody.env so they survive image upgrades.
# Environment variables win over the file (and are written back to it, so a
# rotated master key sticks); missing values are generated once.
load_or_generate_operator_values() {
	local env_file="$state_dir/kody.env"
	local env_admin="${KODY_ADMIN_TOKEN:-}" env_master="${KODY_MASTER_KEY:-}"
	if [[ -f "$env_file" ]]; then
		# shellcheck disable=SC1090
		set -a && source "$env_file" && set +a
	fi
	local generated=0
	if [[ -n "$env_admin" && "$env_admin" != "${KODY_ADMIN_TOKEN:-}" ]]; then generated=1; fi
	if [[ -n "$env_master" && "$env_master" != "${KODY_MASTER_KEY:-}" ]]; then generated=1; fi
	if [[ -n "$env_admin" ]]; then KODY_ADMIN_TOKEN="$env_admin"; fi
	if [[ -n "$env_master" ]]; then KODY_MASTER_KEY="$env_master"; fi
	if [[ -z "${KODY_ADMIN_TOKEN:-}" ]]; then
		KODY_ADMIN_TOKEN="$(random_hex 32)"
		generated=1
	fi
	if [[ -z "${KODY_MASTER_KEY:-}" ]]; then
		KODY_MASTER_KEY="$(random_hex 32)"
		generated=1
	fi
	export KODY_ADMIN_TOKEN KODY_MASTER_KEY
	if [[ "$generated" == 1 || ! -f "$env_file" ]]; then
		mkdir -p "$state_dir"
		umask 077
		{
			echo "# Generated by kody-celld on $(date -u +%FT%TZ). Back this file up: losing"
			echo "# KODY_MASTER_KEY makes every stored user secret unreadable."
			echo "KODY_ADMIN_TOKEN=$KODY_ADMIN_TOKEN"
			echo "KODY_MASTER_KEY=$KODY_MASTER_KEY"
		} >"$env_file"
		umask 022
		echo "[kody-celld] wrote operator values to $env_file (admin token + master key)."
		echo "[kody-celld] read the admin token with: docker compose exec kody cat $env_file"
	fi
}

run_single() {
	load_or_generate_operator_values
	export KODY_PUBLIC_URL="${KODY_PUBLIC_URL:-http://localhost:$port}"
	mkdir -p "$state_dir/celld"
	# celld dev keeps its state in <project>/.celld/dev; point it at the volume.
	if [[ ! -L /app/.celld ]]; then
		rm -rf /app/.celld
		ln -s "$state_dir/celld" /app/.celld
	fi
	# .dev.vars overrides wrangler.jsonc vars; celld dev reads it beside the config.
	umask 077
	{
		echo "KODY_ADMIN_TOKEN=$KODY_ADMIN_TOKEN"
		echo "KODY_MASTER_KEY=$KODY_MASTER_KEY"
		echo "KODY_PUBLIC_URL=$KODY_PUBLIC_URL"
		echo "KODY_ALLOW_INSECURE_SECRET_HOSTS=${KODY_ALLOW_INSECURE_SECRET_HOSTS:-}"
		echo "KODY_MASTER_KEY_PREVIOUS=${KODY_MASTER_KEY_PREVIOUS:-}"
		# Empty on purpose: the wrangler.jsonc dev value allows loopback rendering for smoke only.
		echo "KODY_BROWSER_ALLOW_PRIVATE_HOSTS=${KODY_BROWSER_ALLOW_PRIVATE_HOSTS:-}"
		for tunable in $(tunable_vars); do
			echo "$tunable=${!tunable}"
		done
	} >/app/.dev.vars
	umask 022
	echo "[kody-celld] single node: MCP at $KODY_PUBLIC_URL/mcp (listening on 0.0.0.0:$port)"
	exec celld dev /app --host 0.0.0.0 --port "$port" --no-watch ${CELLD_DEV_FLAGS:-}
}

run_deploy() {
	: "${CELLD_BUCKET:?CELLD_BUCKET is required (s3://bucket[/prefix])}"
	if [[ "${KODY_CREATE_BUCKET:-0}" == 1 ]]; then
		node /app/docker/ensure-bucket.mjs
	fi
	node /app/scripts/render-fleet-config.mjs
	exec celld deploy /app/wrangler.fleet.jsonc "$@"
}

run_node() {
	: "${CELLD_BUCKET:?CELLD_BUCKET is required (s3://bucket[/prefix])}"
	export CELLD_ADDR="${CELLD_ADDR:-0.0.0.0:$port}"
	exec celld "$@"
}

case "$mode" in
single) run_single "$@" ;;
deploy) run_deploy "$@" ;;
node) run_node "$@" ;;
celld) exec celld "$@" ;;
sh | bash) exec bash "$@" ;;
*)
	echo "unknown mode '$mode' (expected single|deploy|node|celld|sh)" >&2
	exit 64
	;;
esac
